# Generated by Django 4.2.6 on 2023-10-16 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_cursos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'verbose_name': 'Cursos', 'verbose_name_plural': 'Cursos'},
        ),
    ]
