# Generated by Django 4.2.6 on 2023-10-16 00:28

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_cursos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='utilesCurso',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/cursos'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='reglamento',
            name='archivo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/reglamento'), upload_to=''),
        ),
    ]
