# Generated by Django 4.2.6 on 2023-10-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_cursos_utilescurso_alter_reglamento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglamento',
            name='archivo',
            field=models.ImageField(upload_to='uploads/reglamento/'),
        ),
    ]
