# Generated by Django 4.2.6 on 2023-10-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_alter_reglamento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='utilesCurso',
            field=models.FileField(upload_to='media/uploads/cursos/'),
        ),
        migrations.AlterField(
            model_name='reglamento',
            name='archivo',
            field=models.ImageField(upload_to='media/uploads/reglamento/'),
        ),
    ]
