# Generated by Django 3.1.2 on 2023-11-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_alter_cursos_utilescurso_alter_reglamento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reglamento',
            name='archivo',
            field=models.FileField(upload_to='media/uploads/reglamento/'),
        ),
        migrations.AlterField(
            model_name='reglamento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
