# Generated by Django 3.1.2 on 2023-11-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20231107_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdBasica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edbasica', models.CharField(max_length=150)),
                ('utilesCurso', models.FileField(upload_to='uploads/edbasica/')),
            ],
            options={
                'verbose_name': 'EdBasica',
                'verbose_name_plural': 'EnseñanzaBásica',
            },
        ),
        migrations.CreateModel(
            name='NivTransicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivtransicion', models.CharField(max_length=150)),
                ('utilesCurso', models.FileField(upload_to='uploads/nivtransicion/')),
            ],
            options={
                'verbose_name': 'NivTransicion',
                'verbose_name_plural': 'NivelTransición',
            },
        ),
        migrations.DeleteModel(
            name='Cursos',
        ),
    ]
