# Generated by Django 3.1.2 on 2023-11-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20231108_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('utilesCurso', models.FileField(upload_to='uploads/tools/')),
            ],
            options={
                'verbose_name': 'Utiles Centro',
                'verbose_name_plural': 'Utiles Barra Central',
            },
        ),
        migrations.CreateModel(
            name='ToolsLeft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('utilesCurso', models.FileField(upload_to='uploads/tools/')),
            ],
            options={
                'verbose_name': 'Utiles Izquierda',
                'verbose_name_plural': 'Utiles Barra Izquierda',
            },
        ),
        migrations.CreateModel(
            name='ToolsRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('utilesCurso', models.FileField(upload_to='uploads/tools/')),
            ],
            options={
                'verbose_name': 'Utiles Derecha',
                'verbose_name_plural': 'Utiles Barra Derecha',
            },
        ),
        migrations.DeleteModel(
            name='EdBasica',
        ),
        migrations.DeleteModel(
            name='NivTransicion',
        ),
    ]
